# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumname_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
